### ISSUE TITLE
msaR seqlogo for nucleotide sequences

### ISSUE THREAD

**Issue by haruosuz** [zachcp/msaR#10]
The `msaR` function was applied to DNA multiple alignment with 3 rows and 5000 columns. As shown in attachment, a full alignment (5000 columns) did not generate seqlogo, while a shorter alignment (2000 columns) generated seqlogo in which some columns of nucleotides (A T G C N) were not shown. Is there any documentation for the `colorscheme` argument of the msaR function?
```
colorscheme	
optional. Default "nucleotide". The color scheme to use. Can be one of the following: "buried","cinema","clustal","clustal2","helix","hydro","lesk","mae","nucleotide","purine","strand","taylor","turn","zappo"
```

[my_msaR_dna.zip](https://github.com/zachcp/msaR/files/5577461/my_msaR_dna.zip)

**Comment by zachcp** [comment]
@haruosuz ,

Thanks for your interest in this package. It is a relatively thin wrapper around the [msa javascript library](https://github.com/wilzbach/msa) and as such does little more than pass along the correct arguments/data to the JS instantiation.

I implemented the seqlogo option because that is what the javascript library accepts but any issues with the internals is more than I can support maintenance for.  I can replicate your issues but I cannot solve the underlying JS. Considering that the JS library has also not been updated in 4 years, I think this might not be the way to go. 

If you are looking for seqlogo features from R, perhaps the [seqlogo](https://github.com/wilzbach/msa) package is a better option. An alternative JS library that seems to be under current development is [available here](https://alignmentviewer.org/).

zach cp
