### ISSUE TITLE
allow adjustments to overview rectangle box height/width

### ISSUE THREAD

**Issue by jkorstia** [zachcp/msaR#6]
Hi Zach!

I really like that you added the option to adjust the size of the entire overview box!  For my particular project, I was hoping to adjust the height of the rectangles representing each base in the overview box.  I know the original msa has that option, but I have not been able to figure out how to do it in this R package.  Could you add that option to yours or suggest how I might do the same?

Thanks for any help you could offer!

-Jenny

**Comment by zachcp** [comment]
Hi Jenny,


Its been a while since I looked at the code but I could take a crack at implementing it. It would be helpful, though, if you can provide 2 things. 

1. a picture or some other visual of what you are trying to do. 
2. link to an example in the JS code.

 if I know what you're trying to do and you can help/refresh me on the JS API, I should be able to put it together.

zach cp

**Comment by jkorstia** [comment]
Hi Zach,

Thanks for replying so fast and being willing to help!!  I have done a lot of experimenting and I was able to work through your code and the original msaR script and create what I needed.  I'm working on polishing it up and putting what I have made here eventually.  I really appreciate your willingness to help and you sharing your code!

Thanks,
-Jenny
